import os, sys
import numpy as np

#This program opens an ASCII file generated by the LNC program and outputs a
#Pandas dataframe with the data and relevant metadata
#Note: Input file must be either a 1-D temporal average or a
#"Single Table with Time in the X Axis vs Altitude in the Y Axis"
#NOT A "Series of consecutively listed profiles"

def lnc_ascii_reader(filepath, dim=2):
    import pandas.io as pio
    import os,sys
    
    print 'Opening '+filepath
    df = pio.parsers.read_csv(filepath,sep='s*',header=2,index_col=0,parse_dates=True)

    return df
        
