import os, sys
import numpy as np

#This program opens a file generated by the 
def lnc_ascii_reader(filepath, dim=2):
    print 'Oening '+filepath
    f = open(filepath,'r')
    for line in f:
        
