#This program opens an ASCII file generated by the LNC program and outputs a
#Pandas dataframe with the data and relevant metadata
#Note: Input file must be either a 1-D temporal average or a
#"Single Table with Time in the X Axis vs Altitude in the Y Axis"
#NOT A "Series of consecutively listed profiles"

def lnc_reader(filepath):
    import pandas as pan
    import numpy as np
    import re
    import csv
    from dateutil.parser import parse
    from decimal import *

    product = []
    

    [fname,fext] = filepath.split('.')
    fout_name = fname+'_proc'
    fout_name = fout_name+'.'+fext
    
    bigspace = re.compile('\s\s\s+')
    fin = open(filepath, 'rb')
    fout = open(fout_name, 'w')
    
    for line in fin:
        if not product:
            product.append(line)
        elif len(line) == 2:
            continue  
        else:
            line = bigspace.sub(',',line)+'\n'
            fout.write(line)
            
    fin.close()
    fout.close()
    temp = []

    for row in csv.reader(open(fout_name,'rb'), delimiter=','):
        temp.append(row)

    temparray = np.array(temp).T

    index = []
    for i in temparray[1:-1,0]: index.append(parse(i)) 

    columns = np.array(temparray[0,1:],dtype='float')
    
    data = temparray[1:-1,1:]


    df = pan.DataFrame(data,index=index,columns=columns,dtype='float')

    return df       

if __name__=='__main__':

    filepath = 'C:\Users\User\TransPAC_Code\UBC_03242010_BR1064.txt'
    readout = lnc_reader(filepath)
 
